name: sciterna2
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - numba
  - pyyaml
  - tqdm
  - networkx
  - dendropy
  - biopython
  - ete3
  - graphviz
  - python-graphviz
  - jupyterlab
  - ipykernel
  - ipywidgets
